
// export const DELETE_COMPLETED_TASK = 'DELETE_COMPLETED_TASK';

export const TASK_DELETE_START = 'TASK_DELETE_START';
export const TASK_DELETE_ERROR = 'TASK_DELETE_ERROR';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';

export const TASK_DELETE_FETCH_START = 'TASK_DELETE_FETCH_START';
export const TASK_DELETE_FETCH_SUCCESS = 'TASK_DELETE_FETCH_SUCCESS';
export const TASK_DELETE_FETCH_ERROR = 'TASK_DELETE_FETCH_ERROR';

export const TASK_COMPLETE_FETCH_START = 'TASK_COMPLETE_FETCH_START';
export const TASK_COMPLETE_FETCH_SUCCESS = 'TASK_COMPLETE_FETCH_SUCCESS';
export const TASK_COMPLETE_FETCH_ERROR = 'TASK_COMPLETE_FETCH_ERROR';
export const TASK_COMPLETE_START = 'TASK_COMPLETE_START';
export const TASK_COMPLETE_SUCCESS = 'TASK_COMPLETE_SUCCESS';
export const TASK_COMPLETE_ERROR = 'TASK_COMPLETE_ERROR';

export const TODO_TASK_FETCH_START = 'TODO_TASK_FETCH_START';
export const TODO_TASK_FETCH_SUCCESS = 'TODO_TASK_FETCH_SUCCESS';
export const TODO_TASK_FETCH_ERROR = 'TODO_TASK_FETCH_ERROR';
export const TODO_TASK_FORM_STATE_HANDLER = 'TODO_TASK_FORM_STATE_HANDLER';
export const TODO_TASK_COMPLETE_START = 'TODO_TASK_COMPLETE_START';
export const TODO_TASK_COMPLETE_SUCCESS = 'TODO_TASK_COMPLETE_SUCCESS';
export const TODO_TASK_COMPLETE_ERROR = 'TODO_TASK_COMPLETE_ERROR';

export const DELETE_COMPLETED_TASK_START = 'DELETE_COMPLETED_TASK_START';
export const DELETE_COMPLETED_TASK_SUCCESS = 'DELETE_COMPLETED_TASK_SUCCESS';
export const DELETE_COMPLETED_TASK_ERROR = 'DELETE_COMPLETED_TASK_ERROR';

// export const SAVE_TASKS = 'SAVE_TASKS';
export const SAVE_TASKS_START = 'SAVE_TASKS_START';
export const SAVE_TASKS_SUCCESS = 'SAVE_TASKS_SUCCESS';
export const SAVE_TASKS_ERROR = 'SAVE_TASKS_ERROR';